export const EMAIL_SERVICE_ID = process.env.REACT_APP_EMAIL_SERVICE_ID;
export const EMAIL_SERVICE_TEMPLATE = process.env.REACT_APP_EMAIL_SERVICE_TEMPLATE;
export const EMAIL_SERVICE_PUBLIC_KEY = process.env.REACT_APP_EMAIL_SERVICE_PUBLIC_KEY;
export const BASE_WEB_URL = process.env.REACT_APP_BASE_WEB_URL;
